application: engineapp
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: css
  static_dir: war/css

- url: /war/js
  static_dir: war/js

- url: /war/img
  static_dir: war/img

- url: /war/mail
  static_dir: war/mail

- url: /(.+\.(gif|png|jpg|bmp|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|bmp|css|js)$
  application_readable: true

- url: .*
  script: .\war\index.html

